import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { Col, Container, Row } from 'reactstrap'
import Header from 'components/Header/Header'
import Footer from 'components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Maze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        {/* BANNER SECTION */}
        <section className={`${styles.banner} text-center`}>
          <Container>
            <Row>
              <Col>
                <h1>All-In-One Platform for <br /> Global Growth</h1>
                <p>Achieve new levels of productiveness & reduce the costs and<br />
                  errors associated with manual tasks</p>
              </Col>
            </Row>
          </Container>
        </section>
        {/* BANNER SECTION */}

        {/* ABOUT SECTION */}
        <section className={`${styles.aboutSec}`}>
          <Container>
            <Row className='justify-content-center'>
              <Col className='col-md-9'>
                <div className={`${styles.domainSearch}`}>
                  <Row>
                    <Col className='col-md-6'>
                      <h3 className='fw-semibold text-start'>Domain Name Search <br /> Buy a Domain In Minutes</h3>
                    </Col>
                    <Col className='col-md-6'>
                      <p className='text-end'>Your domain helps people find you online and makes a first impression. Find one that represents you perfectly.</p>
                    </Col>
                    <Col className='col-md-12'>
                      <div className={`${styles.inputField}`}>
                        <input className='form-control' type="email" placeholder='Enter the domain of your choice' />
                        <button className="btn btn-md btn-primary text-light" type='submit'>Search Domain</button>
                      </div>
                    </Col>
                  </Row>
                </div>
              </Col>
            </Row>
            <Row>
              <Col className='col-md-6'>
                <h2 className='mb-5'>Say Hello to <span>Maze Digital</span></h2>
                <h4 className='mb-3'>Excelling in Security and Protection</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              </Col>
            </Row>
          </Container>
        </section>
        {/* ABOUT SECTION */}

        {/* WHAT WE DO SECTION */}
        <section className={`${styles.services}`}>
          <Container>
            <Row className='justify-content-center'>
              <Col className='col-md-4 text-center mb-3'>
                <h4 className='fw-semibold mb-2'>WHAT WE DO</h4>
                <p className='fw-normal'>Leverage agile frameworks to provide a robust synopsis for high level overviews.</p>
              </Col>
            </Row>
            <Row>
              <Col className='col-md-3'>
                <div className={`${styles.card}`}>
                  <img src={process.env.APP_URL + '/images/icon-1.svg'} alt="icon" />
                  <h2>UI/UX Design</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis . </p>
                </div>
              </Col>
              <Col className='col-md-3'>
                <div className={`${styles.card}`}>
                  <img src={process.env.APP_URL + '/images/icon-2.svg'} alt="icon" />
                  <h2>Design Service</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nos.</p>
                </div>
              </Col>
              <Col className='col-md-3'>
                <div className={`${styles.card}`}>
                  <img src={process.env.APP_URL + '/images/icon-3.svg'} alt="icon" />
                  <h2>Web Development</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
              </Col>
              <Col className='col-md-3'>
                <div className={`${styles.card}`}>
                  <img src={process.env.APP_URL + '/images/icon-4.svg'} alt="icon" />
                  <h2>Ecommerce</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        {/* WHAT WE DO SECTION */}

        {/* SERVICES SECTION */}
        <section className={`${styles.services_section}`}>
          <Container>
            <Row className='justify-content-center'>
              <Col className='col-md-10'>
                <Row className='align-items-center'>
                  <Col className='col-md-6'>
                    <h2><span className='d-block'>LOREM IPSUM</span> Feature-Rich <br />Ecommerce Websites</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut </p>
                    <button className='btn-style'>VIEW CASE STUDY</button>
                  </Col>
                  <Col className='col-md-6'>
                    <figure className='text-end'>
                      <img src={process.env.APP_URL + '/images/service-1.svg'} alt="image" />
                    </figure>
                  </Col>
                </Row>
                <Row className='align-items-center flex-row-reverse'>
                  <Col className='col-md-6'>
                    <h2><span className='d-block'>LOREM IPSUM</span> Feature-Rich <br />Ecommerce Websites</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut </p>
                    <button className='btn-style'>VIEW CASE STUDY</button>
                  </Col>
                  <Col className='col-md-6'>
                    <figure className='text-start'>
                      <img src={process.env.APP_URL + '/images/service-2.svg'} alt="image" />
                    </figure>
                  </Col>
                </Row>
                <Row className='align-items-center'>
                  <Col className='col-md-6'>
                    <h2><span className='d-block'>LOREM IPSUM</span> Feature-Rich <br />Ecommerce Websites</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut </p>
                    <button className='btn-style'>VIEW CASE STUDY</button>
                  </Col>
                  <Col className='col-md-6'>
                    <figure className='text-end'>
                      <img src={process.env.APP_URL + '/images/service-3.svg'} alt="image" />
                    </figure>
                  </Col>
                </Row>
              </Col>
            </Row>
          </Container>
        </section>
        {/* SERVICES SECTION */}

        <Footer />
      </main>
    </>
  )
}
